### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by InfoSecured** [plexinc/webhooks-slack#8]
I set this up in Heroku and added the heroku app url to the Plex webhook. Is there anything else I have to do to get this to work?

**Comment by elan** [comment]
It's been working over here 😅

**Comment by InfoSecured** [comment]
Ah, yes. I did get it working. There was just a huge delay, probably from
the heroku side.


Jason S. Lazerus, M.S., GCFA, GPEN, GCIH, GCFE, GCED, GSEC

**Comment by elan** [comment]
Lovely, glad to hear.
